#ifndef _PROTO_H
#define _PROTO_H
enum class REQUEST_TYPE{
    ACCOUNT_CHECK=0,
    FETCH_PLAYER_INFO=1,
    FETCH_PLAYERS_INFO=2,
    REGIST=3,
    LOGIN=4,
    LOGOUT=5,
    FETCH_LOBBY_INFO=6,
    FETCH_ROOM_INFO=7,
    SITDOWN=8,
    LEAVE=9,
    READYGO=10,
    PLACECHESS=11,
    UPDATE_GAMERESULT=12,
    SEND_MSG=13,
    GROUP_CHAT=14,
    NICKNAME_CHECK=15,
};

enum class RESPONSE_TYPE{
    FETCH_PLAYER_INFO_SUCCESS=0,
    FETCH_PLAYER_INFO_FAILED=1,
    FETCH_PLAYERS_INFO_SUCCESS=2,
    FETCH_PLAYERS_INFO_FAILED=3,
    REGIST_SUCCESS=4,
    REGIST_FAILED=5,
    LOGIN_SUCCESS=6,
    LOGIN_FAILED=7,
    LOGOUT_SUCCESS=8,
    LOGOUT_FAILED=9,
    FETCH_LOBBY_INFO_SUCCESS=10,
    FETCH_LOBBY_INFO_FAILED=11,
    FETCH_ROOM_INFO_SUCCESS=12,
    FETCH_ROOM_INFO_FAILED=13,
    BROADCAST_SITDOWN=14,
    SITDOWN_SUCCESS=15,
    SITDOWN_FAILED=16,
    BROADCAST_LEAVE=17,
    LEAVE_SUCCESS=18,
    LEAVE_FAILED=19,
    SINGLECAST_READYGO=20,
    BROADCAST_READYGO=21,
    READYGO_SUCCESS=22,
    READYGO_FAILED=23,
    PLACECHESS_SUCCESS=24,
    PLACECHESS_FAILED=25,
    SINGLECAST_PLACECHESS=26,
    UPDATE_GAMERESULT_SUCCESS=27,
    UPDATE_GAMERESULT_FAILED=28,
    SEND_MSG_SUCCESS=29,
    SEND_MSG_FAILED=30,
    BROADCAST_SOMEONE_UP=31,
    BROADCAST_SOMEONE_DOWN=32,
    GROUP_CHAT_MSG=33,
    GROUP_CHAT_SUCCESS=34,
    GROUP_CHAT_FAILED=35,
    SINGLECAST_CHAT=36,
    BROADCAST_GAMERESULT_UPDATE=37,
    ACCOUNT_CHECK_SUCCESS=38,
    ACCOUNT_CHECK_FAILED=39,
    NICKNAME_CHECK_SUCCESS=40,
    NICKNAME_CHECK_FAILED=41,
    SINGLECAST_UPDATE_PLAYER=42,
    BROADCAST_UPDATE_PLAYER=43,
    UPDATE_ROOM_SUCCESS=44,
    UPDATE_ROOM_FAILED=45,
    BROADCAST_UPDATE_ROOM=46,
    SINGLECAST_UPDATE_GAMERESULT=47
};

enum class ORDER{
    LEFT=0,
    RIGHT=1
};

enum class STATE{
    OUTLINE=0,
    OTHER=1,
    IDLE=2,
    READY=3,
    GAMING=4
};

enum class ROOM_STATE{
    WATING=0,
    READY=1,
    GAMING=2
};
#endif
